nameOverride: ""
fullnameOverride: ""

service:
  port: 9000
  metricsEndpoint:
    enabled: false

iamRole: arn:aws:iam::479720515435:role/ecsInstanceRole
image:
  repository: flowcommerce/ben-test-api
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: "3400Mi"
    cpu: 1
  requests:
    memory: "3400Mi"
    cpu: .05

jvmMemory: 3000

nodeSelector: {} 
affinity: {}
tolerations: {} 

ingress:
  enabled: true
  gateways:
    - key: ben-test-flow-io
      tld: api.flow.io
      hosts:
        - ben-test.api.flow.io
    - key: ben-test-flow-pub
      tld: flo.pub
      hosts:
        - ben-test.flo.pub

services:
  live:
    hosts:
      - ben-test
      - ben-test.api.flow.io
      - ben-test.flo.pub
    gateways:
      - mesh
      - ben-test-flow-io
      - ben-test-flow-pub
    stages:
      - deployment: live
        weight: 100

deployments:
  live:
    minReplicas: 1
    maxReplicas: 1
    maxUnavailable: 1
    disruptionBudgetEnabled: true
    targetCPUUtilizationPercentage: 80
    version: #from commandline
    strategy: RollingUpdate